name: nl_transit
version: '1.0.0'
profile: nl_transit

model-paths: ['models']
macro-paths: ['macros']
test-paths: ['tests']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  nl_transit:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
